// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCf98zeWhAu--jWnL6q2puDIL1ZqepDDQ',
    appId: '1:251220245675:android:6b4002d61e248540cacbee',
    messagingSenderId: '251220245675',
    projectId: 'unitools-f5be3',
    databaseURL: 'https://unitools-f5be3-default-rtdb.firebaseio.com',
    storageBucket: 'unitools-f5be3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMzzrIL_DZzeiRkShBqGkXPbKhXOFpP3k',
    appId: '1:251220245675:ios:127ced09d1eba5a6cacbee',
    messagingSenderId: '251220245675',
    projectId: 'unitools-f5be3',
    databaseURL: 'https://unitools-f5be3-default-rtdb.firebaseio.com',
    storageBucket: 'unitools-f5be3.firebasestorage.app',
    iosBundleId: 'com.example.storekeeper',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTEJhfU6puPHgHexKZrWQ7EjcZFwnX36k',
    appId: '1:251220245675:web:32e34f400fb7edaccacbee',
    messagingSenderId: '251220245675',
    projectId: 'unitools-f5be3',
    authDomain: 'unitools-f5be3.firebaseapp.com',
    databaseURL: 'https://unitools-f5be3-default-rtdb.firebaseio.com',
    storageBucket: 'unitools-f5be3.firebasestorage.app',
    measurementId: 'G-TFQVC9KPD7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMzzrIL_DZzeiRkShBqGkXPbKhXOFpP3k',
    appId: '1:251220245675:ios:127ced09d1eba5a6cacbee',
    messagingSenderId: '251220245675',
    projectId: 'unitools-f5be3',
    databaseURL: 'https://unitools-f5be3-default-rtdb.firebaseio.com',
    storageBucket: 'unitools-f5be3.firebasestorage.app',
    iosBundleId: 'com.example.storekeeper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTEJhfU6puPHgHexKZrWQ7EjcZFwnX36k',
    appId: '1:251220245675:web:5861c20f5a3105a6cacbee',
    messagingSenderId: '251220245675',
    projectId: 'unitools-f5be3',
    authDomain: 'unitools-f5be3.firebaseapp.com',
    databaseURL: 'https://unitools-f5be3-default-rtdb.firebaseio.com',
    storageBucket: 'unitools-f5be3.firebasestorage.app',
    measurementId: 'G-3XWBV1T00C',
  );

}